name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '93'
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t luckyraul/regression:${{ matrix.version }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=luckyraul/regression:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/regression:${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
